DROP TABLE IF EXISTS detalle_pedido;
DROP TABLE IF EXISTS detalle_pedido_automatico;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS pedido_automatico;
DROP TABLE IF EXISTS precio;
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS lista_de_precios;
DROP TABLE IF EXISTS direccion;
DROP TABLE IF EXISTS metodo_pago;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS usuario;

CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    rubro VARCHAR(255),
    unidad VARCHAR(255),
    costo_total DECIMAL(10, 2)
);

-- Recrear lista_de_precios y precio para mantener la coherencia
CREATE TABLE lista_de_precios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE precio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    lista_de_precios_id BIGINT NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (producto_id) REFERENCES producto(id),
    FOREIGN KEY (lista_de_precios_id) REFERENCES lista_de_precios(id)
);

-- Las siguientes tablas se recrearán con el esquema por defecto de JPA al iniciar la aplicación
-- o se deberán definir sus CREATE TABLE aquí si no se usa JPA para su creación automática.